# Generated by Django 4.1.1 on 2022-09-30 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('profile', models.ImageField(upload_to='Company')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField()),
                ('imgUrl', models.URLField(max_length=1000)),
                ('linkType', models.BooleanField()),
                ('noOfMembers', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('Group', 'Group'), ('Channel', 'Channel'), ('Bot', 'Bot'), ('Stickers', 'Stickers')], max_length=20)),
                ('linkId', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.company')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.language')),
                ('tag', models.ManyToManyField(blank=True, related_name='tag_blogs', to='blog.tag')),
            ],
        ),
    ]
