# Generated by Django 2.1.15 on 2023-03-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
