# Generated by Django 4.1.1 on 2022-10-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='linkType',
        ),
        migrations.AlterField(
            model_name='link',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
