# Generated by Django 2.1.15 on 2023-11-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_link_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='link',
            name='paidAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
