# Generated by Django 2.1.15 on 2024-01-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_link_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='mail',
            field=models.EmailField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
