# Generated by Django 4.1.1 on 2022-10-01 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_link_linktype_alter_link_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.company'),
        ),
    ]
