# Generated by Django 2.1.15 on 2024-03-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20240120_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='number_of_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
