# Generated by Django 2.1.15 on 2022-10-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
