# Generated by Django 2.1.15 on 2023-03-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0003_auto_20221021_0632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('viewed', 'date')},
        ),
    ]
