# Generated by Django 2.1.15 on 2023-04-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0004_auto_20230308_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
    ]
