# Generated by Django 2.1.15 on 2024-01-26 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spin',
            name='last_spin',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 15, 30, 2, 376135, tzinfo=utc)),
        ),
    ]
