# Generated by Django 2.1.15 on 2024-01-28 16:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20240126_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='spin',
            name='today_spin_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spin',
            name='last_spin',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 28, 14, 12, 23, 879109, tzinfo=utc)),
        ),
    ]
